[project]
name = "monitoramento-medico-multimodal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "samuelmaxi", email = "samuelgaraujo87@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "gdown>=6.4.0",
    "python-dotenv>=1.2.3",
]

