[project]
name = "monitoramento-medico-multimodal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "samuelmaxi", email = "samuelgaraujo87@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "azure-cognitiveservices-speech>=1.38.0",
    "azure-ai-textanalytics>=5.3.0",
    "azure-storage-blob>=12.25.0",
    "fastapi>=0.141.1",
    "gdown>=6.4.0",
    "python-dotenv>=1.2.3",
    "python-multipart>=0.0.32",
    "uvicorn[standard]>=0.54.0",
]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=9.1.1",
]

